import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const output=Outfit({subsets:['latin']});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={output.className}
      >
        {children}
      </body>
    </html>
  );
}
